
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "flex-start",
    padding: 32,
    backgroundColor: "#232946",
  },
  titulo: {
    fontSize: 28,
    fontWeight: "900",
    color: "#eebbc3",
    marginBottom: 28,
    textAlign: "left",
    letterSpacing: 1.5,
    textShadowColor: "#121629",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  botao: {
    backgroundColor: "#eebbc3",
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginVertical: 12,
    borderRadius: 16,
    width: "100%",
    alignItems: "center",
    shadowColor: "#121629",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  botaoTexto: {
    color: "#232946",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  modalContainer: {
    flex: 1,
    padding: 32,
    paddingTop: 60,
    backgroundColor: "#121629",
  },
  fecharBotao: {
    backgroundColor: "#f6c90e",
    alignSelf: "flex-end",
    padding: 10,
    borderRadius: 8,
  },
  fecharTexto: {
    color: "#232946",
    fontWeight: "bold",
    fontSize: 16,
  },
  frase: {
    marginTop: 24,
    fontSize: 18,
    fontStyle: "italic",
    textAlign: "center",
    color: "#f6c90e",
    backgroundColor: "#393e6a",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#232946",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  mensagemBox: {
    marginTop: 18,
    backgroundColor: "#393e6a",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    shadowColor: "#232946",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  input: {
    borderWidth: 2,
    borderColor: "#eebbc3",
    borderRadius: 12,
    width: "100%",
    padding: 12,
    marginBottom: 16,
    backgroundColor: "#393e6a",
    color: "#eebbc3",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "center",
    shadowColor: "#232946",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  resultado: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: "bold",
    color: "#f6c90e",
    textAlign: "center",
    backgroundColor: "#232946",
    padding: 10,
    borderRadius: 8,
    shadowColor: "#eebbc3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  label: {
    fontSize: 16,
    color: "#eebbc3",
    marginBottom: 6,
    marginTop: 10,
    fontWeight: "bold",
  },
  picker: {
    backgroundColor: "#393e6a",
    color: "#eebbc3",
    borderRadius: 12,
    marginBottom: 16,
    width: "100%",
  },
  item: {
    fontSize: 18,
    padding: 12,
    backgroundColor: "#eebbc3",
    color: "#232946",
    borderRadius: 10,
    marginVertical: 6,
    fontWeight: "bold",
    shadowColor: "#232946",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  painelCards: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 18,
    marginTop: 10,
    marginBottom: 10,
  },
  card: {
    backgroundColor: "#eebbc3",
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 22,
    margin: 8,
    minWidth: 140,
    alignItems: "center",
    shadowColor: "#232946",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  cardTitulo: {
    color: "#232946",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 1,
  },
  janelaModalFundo: {
    flex: 1,
    backgroundColor: "rgba(35,41,70,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  janelaModal: {
    backgroundColor: "#121629",
    borderRadius: 24,
    padding: 24,
    minWidth: "80%",
    shadowColor: "#eebbc3",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
});
